### ISSUE TITLE
How to read enums with a fixed representation?

### ISSUE THREAD

**Issue by dchenbecker** [jam1garner/binread#26]
I'm trying to figure out how to use an enum based on a `u8` field, but it always reads as the first element of the enum no matter what. As an example, here's a minimal example (this code fails). Is this not supported, or am I doing something wrong?

```rust
use binread::{BinRead, BinReaderExt};
use std::io::Cursor;

#[derive(BinRead, Debug, Eq, PartialEq)]
#[repr(u8)]
enum Test {
    One = 0x01,
    Two = 0x02,
    Three = 0x03,
}

fn main() {
    let mut input = Cursor::new(b"\x03");

    let t: Test = input.read_be().unwrap();

    assert!(t == Test::Three);
}
```

**Comment by jam1garner** [comment]
This is not currently something that is automatically derived for you, unfortunately. The way you'd end up making it work is 

```rust
#[derive(BinRead, Debug, Eq, PartialEq)]
#[repr(u8)]
enum Test {
    #[br(magic = 1u8)]
    One = 0x01,
    #[br(magic = 2u8)]
    Two = 0x02,
    #[br(magic = 3u8)]
    Three = 0x03,
}
```

Although I hadn't thought about providing a way to provide an automatic derive for C-style enums with a fixed repr... it's definitely a good idea!

**Comment by dchenbecker** [comment]
Conceptually it feels like this should be something macro-izable, but admittedly I haven't done a lot with macros. Let me see if I can get something working...

**Comment by csnover** [comment]
Here’s some super janky code you could use to get rid of most of the boilerplate until this feature is added to binread:

```rust
#[doc(hidden)]
pub use paste::paste;
#[macro_export]
macro_rules! binread_enum {
    ($name: ident, $size: ty) => {
        impl ::binread::BinRead for $name {
            type Args = ();

            fn read_options<R: ::binread::io::Read + ::binread::io::Seek>(reader: &mut R, options: &::binread::ReadOptions, _: Self::Args) -> ::binread::BinResult<Self> {
                use ::binread::BinReaderExt;
                let last_pos = reader.seek(::std::io::SeekFrom::Current(0))?;
                let value = reader.read_type::<$size>(options.endian)?;
                $crate::paste! {
                    Self::[<from_ $size>](value).ok_or_else(|| ::binread::Error::AssertFail {
                        pos: ::std::convert::TryInto::try_into(last_pos).unwrap(),
                        message: format!(concat!("Invalid ", stringify!($name), " value 0x{:x}"), value),
                    })
                }
            }
        }
    }
}
```

For your example it would be:

```rust
#[derive(Debug, Eq, FromPrimitive, PartialEq)]
#[repr(u8)]
enum Test {
    One = 0x01,
    Two = 0x02,
    Three = 0x03,
}
binread_enum!(Test, u8);
```

Note that this requires adding `num_derive` and `paste` as dependencies, and deriving `num_derive::FromPrimitive` on the enum. Exporting `paste::paste` and using `$crate::paste` in the macro is an artefact of how I am using this in a workspace and so didn’t want to add paste as a dependency to all of the packages. Modify as needed for your situation.

**Comment by csnover** [comment]
I’m working right now on implementing this. There is a separate code path for unit-type enums so it’s half-way there already :-)

I will probably add a new option to the `br` attribute instead of using the built-in `repr` attribute, since binread doesn’t control that attribute and I don’t know if requiring users to force an in-memory `repr` would lead to any accidental performance issues. I guess it can be discussed more at code review time unless someone wants to raise an early objection here.

It would be helpful for me to know if there is some reason why unit-type attributes would ever actually want to use magic, other than for backward compatibility. Is there a real-world use case for this?

It would also probably be good to be able to pass down the correct size to read from a parent struct—I have at least one real-world case where the same enum-type is stored using different sizes in different structs—but I haven’t thought deeply about what would be the right way to implement this yet. I might just leave this out of the initial implementation but I would be happy to hear from anyone who has feelings about it.

**Comment by jam1garner** [comment]
I feel like implementing in a way that allows generics to work (if possible) would be the best route for allowing the call site to determine size
